name: class_cloud
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4
  firebase_messaging: ^15.0.4

  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  go_router: ^14.2.3
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  logging: ^1.2.0
  rive: ^0.13.12
  rxdart: ^0.28.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  uuid: ^4.4.2
  flutter_bloc: ^8.1.6
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  pdf: ^3.10.6
  path_provider: ^2.0.11
  sensors_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
